import React, { useState } from 'react';
import {
  FileText,
  Printer,
  Copy,
  Check,
  X,
} from 'lucide-react';
import {
  VendorScoreResult,
  CriteriaWeights,
  AiRecommendationResponse,
} from '../types';
import { CRITERIA_METADATA } from '../services/scoringEngine';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  rankedVendors: VendorScoreResult[];
  weights: CriteriaWeights;
  recommendation: AiRecommendationResponse | null;
  /** The AI briefing was out of date, so the summary below is the rule-based one for the current inputs. */
  isBriefingRefreshed?: boolean;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  rankedVendors,
  weights,
  recommendation,
  isBriefingRefreshed = false,
}) => {
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied' | 'failed'>('idle');

  if (!isOpen) return null;

  const winner = rankedVendors[0];
  const runnerUp = rankedVendors[1];
  const reportDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const generateMarkdown = () => {
    return `# NOVA MANUFACTURING LTD. — PROCUREMENT EVALUATION MEMORANDUM
**Date:** ${reportDate}  
**RFQ Reference:** RFQ-2026-MFG-048 (Precision Machined Assemblies)  
**Status:** Evaluation Completed (Decision-Support Model)

---

## 1. WEIGHTING PROFILE
- **Cost:** ${weights.cost}%
- **Quality:** ${weights.quality}%
- **Delivery:** ${weights.delivery}%
- **Reliability:** ${weights.reliability}%
- **Sustainability:** ${weights.sustainability}%
*Total Weight Enforced: 100%*

---

## 2. DETERMINISTIC VENDOR RANKINGS
| Rank | Vendor | Overall Score | Cost | Quality | Delivery | Reliability | ESG | Status |
|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---|
${rankedVendors
  .map(
    (v) =>
      `| #${v.rank} | ${v.name} | **${v.overallScore.toFixed(2)}** | ${v.criteria.cost} | ${v.criteria.quality} | ${v.criteria.delivery} | ${v.criteria.reliability} | ${v.criteria.sustainability} | ${
        v.isRecommended
          ? 'Recommended'
          : v.isAlternative
          ? 'Primary Backup'
          : 'Qualified'
      } |`
  )
  .join('\n')}

---

## 3. EXECUTIVE RECOMMENDATION
**Recommended Supplier:** ${recommendation?.recommendedVendor || winner?.name || 'N/A'}  
**Overall Composite Score:** ${winner?.overallScore.toFixed(2)} / 100  
**Dual-Sourcing Runner-Up:** ${recommendation?.bestAlternative.name || runnerUp?.name || 'N/A'} (${runnerUp?.overallScore.toFixed(2)} / 100)

### Why It Ranked Highest:
${recommendation?.whyRankedHighest || 'N/A'}

### Major Strengths:
${recommendation?.majorStrengths.map((s) => `- ${s}`).join('\n') || '- N/A'}

### Identified Vulnerabilities & Mitigation:
${recommendation?.majorWeaknesses.map((w) => `- ${w}`).join('\n') || '- N/A'}

### Dual-Sourcing Contingency:
${recommendation?.bestAlternative.justification || 'N/A'}

### Weight Sensitivity & Trade-offs:
${recommendation?.weightSensitivity || 'N/A'}

---
*Generated by VendorWise AI Decision Support System.*
`;
  };

  // Only report success if the copy really happened (it can be blocked by permissions, and
  // navigator.clipboard does not exist on non-HTTPS pages other than localhost).
  const handleCopy = async () => {
    const text = generateMarkdown();
    let ok = false;
    try {
      await navigator.clipboard.writeText(text);
      ok = true;
    } catch {
      // Fall back to the legacy API.
      const area = document.createElement('textarea');
      area.value = text;
      area.style.position = 'fixed';
      area.style.opacity = '0';
      document.body.appendChild(area);
      area.select();
      try {
        ok = document.execCommand('copy');
      } catch {
        ok = false;
      }
      document.body.removeChild(area);
    }
    setCopyStatus(ok ? 'copied' : 'failed');
    setTimeout(() => setCopyStatus('idle'), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="print-memo-root fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-xs p-4 animate-in fade-in duration-150">
      <div className="print-memo bg-white rounded-xl shadow-2xl border border-slate-200 max-w-3xl w-full max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="no-print p-4 sm:p-5 border-b border-slate-100 flex items-center justify-between bg-slate-50">
          <div className="flex items-center space-x-2.5">
            <div className="w-8 h-8 rounded-lg bg-brand-50 text-brand-600 flex items-center justify-center">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">
                Procurement Evaluation Memorandum
              </h3>
              <p className="text-xs text-slate-500">
                Official decision-support summary for Nova Manufacturing Ltd.
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopy}
              className="inline-flex items-center space-x-1 px-3 py-1.5 text-xs font-semibold rounded-lg border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 transition-colors"
            >
              {copyStatus === 'copied' ? (
                <Check className="w-3.5 h-3.5 text-emerald-600" />
              ) : (
                <Copy className="w-3.5 h-3.5" />
              )}
              <span>
                {copyStatus === 'copied' ? 'Copied' : copyStatus === 'failed' ? 'Copy failed' : 'Copy Markdown'}
              </span>
            </button>
            <button
              onClick={handlePrint}
              className="inline-flex items-center space-x-1 px-3 py-1.5 text-xs font-semibold rounded-lg bg-slate-900 hover:bg-slate-800 text-white shadow-xs transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-slate-600 p-1"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Body Preview */}
        <div className="p-6 overflow-y-auto space-y-6 text-slate-800 text-xs sm:text-sm">
          {isBriefingRefreshed && (
            <div className="no-print rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-900">
              The AI briefing was out of date, so section 3 uses the rule-based summary for the current
              weights and vendors. Re-analyze on the AI Recommendation page to include a fresh AI briefing.
            </div>
          )}
          {/* Memorandum Header */}
          <div className="border-b border-slate-200 pb-4">
            <div className="flex justify-between items-start">
              <div>
                <span className="text-xs font-black uppercase text-brand-700 tracking-wider">
                  Internal Memorandum
                </span>
                <h1 className="text-xl font-black text-slate-900 mt-1">
                  NOVA MANUFACTURING LTD.
                </h1>
                <p className="text-xs text-slate-500">
                  Global Sourcing & Supplier Quality Management Committee
                </p>
              </div>
              <div className="text-right text-xs text-slate-500">
                <div><strong>Date:</strong> {reportDate}</div>
                <div><strong>RFQ Ref:</strong> RFQ-2026-MFG-048</div>
              </div>
            </div>
          </div>

          {/* Criteria Weights Table */}
          <div>
            <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wider mb-2">
              1. Applied Decision Criteria Weights
            </h4>
            <div className="grid grid-cols-5 gap-2 text-center text-xs">
              {(Object.keys(weights) as (keyof CriteriaWeights)[]).map((k) => (
                <div key={k} className="p-2 bg-slate-50 rounded border border-slate-200">
                  <div className="text-slate-500 capitalize">{CRITERIA_METADATA[k].label}</div>
                  <div className="font-extrabold text-slate-900 text-sm">{weights[k]}%</div>
                </div>
              ))}
            </div>
          </div>

          {/* Rankings */}
          <div>
            <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wider mb-2">
              2. Final Comparative Ranking Matrix
            </h4>
            <div className="border border-slate-200 rounded-lg overflow-hidden">
              <table className="w-full text-left text-xs">
                <thead className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
                  <tr>
                    <th className="p-2">Rank</th>
                    <th className="p-2">Vendor</th>
                    <th className="p-2 text-center">Score</th>
                    <th className="p-2 text-center">Cost</th>
                    <th className="p-2 text-center">Quality</th>
                    <th className="p-2 text-center">Delivery</th>
                    <th className="p-2 text-center">Reliability</th>
                    <th className="p-2 text-center">ESG</th>
                    <th className="p-2 text-right">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {rankedVendors.map((v) => (
                    <tr key={v.id} className={v.rank === 1 ? 'bg-emerald-50/40 font-bold' : ''}>
                      <td className="p-2 font-mono">#{v.rank}</td>
                      <td className="p-2">{v.name}</td>
                      <td className="p-2 text-center font-mono">{v.overallScore.toFixed(2)}</td>
                      <td className="p-2 text-center">{v.criteria.cost}</td>
                      <td className="p-2 text-center">{v.criteria.quality}</td>
                      <td className="p-2 text-center">{v.criteria.delivery}</td>
                      <td className="p-2 text-center">{v.criteria.reliability}</td>
                      <td className="p-2 text-center">{v.criteria.sustainability}</td>
                      <td className="p-2 text-right">
                        {v.isRecommended ? 'Recommended' : v.isAlternative ? 'Dual-Source' : 'Qualified'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* AI Executive Recommendation */}
          {recommendation && (
            <div className="space-y-3 pt-2 border-t border-slate-200">
              <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
                3. Executive Recommendation Summary
              </h4>
              <div className="p-3.5 bg-slate-50 rounded-lg border border-slate-200 space-y-2 text-xs">
                <div>
                  <strong className="text-slate-900">Recommended Partner: </strong>
                  <span className="font-bold text-brand-700">{recommendation.recommendedVendor}</span> ({winner?.overallScore}/100)
                </div>
                <p className="text-slate-700 leading-relaxed">
                  {recommendation.whyRankedHighest}
                </p>
                <div className="pt-2">
                  <strong className="text-slate-900">Key Advantages:</strong>
                  <ul className="list-disc pl-4 mt-1 space-y-0.5 text-slate-600">
                    {recommendation.majorStrengths.map((s, idx) => (
                      <li key={idx}>{s}</li>
                    ))}
                  </ul>
                </div>
                <div className="pt-2">
                  <strong className="text-slate-900">Dual-Sourcing Strategy:</strong>
                  <p className="text-slate-600 mt-0.5">
                    {recommendation.bestAlternative.justification}
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
